// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	rpc "zerostream/streamapi/internal/handler/rpc"
	"zerostream/streamapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: StreamapiHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/rpc/list",
				Handler: rpc.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rpc/record",
				Handler: rpc.RecordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rpc/route",
				Handler: rpc.RouteHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
