// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type Point struct {
	Name  string `json:"name"`
	Value int32  `json:"value"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type StreamRpcListRequest struct {
	Name  string `form:"name"`
	Value int32  `form:"value"`
}

type StreamRpcListResponse struct {
	List []*Point `json:"list"`
}

type StreamRpcRecordRequest struct {
	Name  string `form:"name"`
	Value int32  `form:"value"`
}

type StreamRpcRecordResponse struct {
	List []*Point `json:"list"`
}

type StreamRpcRouteResponse struct {
	List []*Point `json:"list"`
}
